language: go

go:
    - 1.6.0
    - 1.5.3
    - 1.4.3

services:
    - mysql

install:
    - go get github.com/go-sql-driver/mysql

before_script:
    - mysql -u root -e 'create database IF NOT EXISTS golib_test'

script:
    - go test -v ./...
